sudo: required
language: java
jdk: oraclejdk8
dist: trusty

services:
  - mysql
  - postgresql
  - mongodb
  - docker

addons:
  postgresql: "9.5"

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - .gradle/
    - node_modules/

before_install:
  - chmod +x gradlew
  - mysql -e 'CREATE DATABASE IF NOT EXISTS `duic-unit-test`;'
  - psql -c 'CREATE DATABASE "duic-unit-test";' -U postgres

install: true

script:
  - ./gradlew clean buildImage --stacktrace

after_success:
  - if [ ! -z "$TRAVIS_TAG" ]; then
      docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD";
      docker push zhudyos/duic;

      ./gradlew copyRelease;
    fi

deploy:
  provider: releases
  user: "kevin70"
  password: "aBp52C/IVk4PO4OXuXVmHwm+3cL0DNpm3RmSMy9ulLi0m4y8CYCVMEfUUGbeypvLBrFT30yUEdMsutPqNjRI7XMfaHM4SEY1xeiGQG3HnXjwlXea+YlG5C3T4DM+fgjmnVI85ZW7Hgqg7l1vPGQutZXBwH/TAZgMf+lu1pwETrKk9W7r5YuKrOJGvPlydWZSQLPQyfjEcvhwxKQeEt+5ujhnFhSYMWcDIfiVKNMJd5Hd/0XivcvXGQEHAQxIOZbla9VZk3DBuuRmDjk9HKHTeM677NDSrnuVp6l28U5DOPHaF8IdjS0nagSM6Uwz9tAyafP1AMld/SYtrHUMG7FjrfoBG8/tMzmPDxsNtA/hcS9PBCJrrAHNkyvvjEYXEIH7bgAsTItAg9E1JDm9a+ZBRbA1DhP6J1IkTZdg5W2DAHVnBm73EZP6z/0jGa5z33yef9LJa92lELlfHn0bTHmlbENQnahAHyrjdhTiBtvYcZPuoFhXLYeXlleCoP8q/iYJ7pyfO03yK8zvUeZAKvZfjPf9QNw2mErqBWi+QEzaBOOIXSkZSVsM3OhrWhMlSZJGBDm5sJxEhUMkBHLga1NcQ1T0v/VySNSnML8oFqQZI3W5lBEqr5fmGoliWKrvJAIlMVPGxvw2//8/La4AF2673P8z8WLVEjGtGkwsSLuvsdM="
  file: "build/releases/*"
  file_glob: true
  skip_cleanup: true
  on:
    repo: zhudyos/duic
    tags: true
